benchmark:
  warmUpIterations: 50
  measurementIterations: 200
  batchSize: 1000
  jdbcBatchSize: 500
  activeTargets:
    - MONGO_NATIVE
    - ORACLE_JDBC
    - ORACLE_MONGO_API
    - ORACLE_RELATIONAL

dataGeneration:
  advisorCount: 3000
  accountCount: 300000
  bookRoleGroupCount: 90000
  bookRoleInvestorCount: 450000
  advisoryContextPoolSize: 15000
  partyRoleIdPoolSize: 30000
  finInstIdPoolSize: 150
  targetSizeGb: 4.5

connections:
  mongoNative:
    uri: "mongodb://localhost:27017/?replicaSet=rs0&w=1&journal=true"
    database: "helix"
  oracleJdbc:
    url: "jdbc:oracle:thin:@(description=(retry_count=0)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=localhost))(connect_data=(service_name=myatp_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    username: "ADMIN"
    password: "Welcome_12345!"
    maxPoolSize: 10
    ordsBaseUrl: "https://localhost:8443/ords/admin"
  oracleMongoApi:
    uri: "mongodb://ADMIN:Welcome_12345!@localhost:27018/admin?authMechanism=PLAIN&authSource=$external&tls=true&tlsInsecure=true&loadBalanced=true&retryWrites=false"
    database: "ADMIN"
