benchmark:
  warmUpIterations: 50
  measurementIterations: 200
  batchSize: 1000
  jdbcBatchSize: 500

dataGeneration:
  advisorCount: 1000
  accountCount: 100000
  bookRoleGroupCount: 30000
  bookRoleInvestorCount: 150000
  advisoryContextPoolSize: 5000
  partyRoleIdPoolSize: 10000
  finInstIdPoolSize: 50
  targetSizeGb: 1.5

connections:
  mongoNative:
    uri: "mongodb://localhost:27017"
    database: "helix"
  oracleJdbc:
    url: "jdbc:oracle:thin:@(description=(retry_count=0)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=localhost))(connect_data=(service_name=myatp_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    username: "ADMIN"
    password: "Welcome_12345!"
    maxPoolSize: 10
  oracleMongoApi:
    uri: "mongodb://ADMIN:Welcome_12345!@localhost:27018/admin?authMechanism=PLAIN&authSource=$external&tls=true&tlsAllowInvalidCertificates=true&loadBalanced=true&retryWrites=false"
    database: "ADMIN"
