benchmark:
  warmUpIterations: 3
  measurementIterations: 10
  batchSize: 500
  jdbcBatchSize: 250

dataGeneration:
  advisorCount: 50
  accountCount: 500
  bookRoleGroupCount: 150
  bookRoleInvestorCount: 750
  advisoryContextPoolSize: 100
  partyRoleIdPoolSize: 200
  finInstIdPoolSize: 10
  targetSizeGb: 0.01

connections:
  mongoNative:
    uri: "mongodb://localhost:27017/?replicaSet=rs0&w=1&journal=true"
    database: "helix"
  oracleJdbc:
    url: "jdbc:oracle:thin:@(description=(retry_count=0)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=localhost))(connect_data=(service_name=myatp_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))"
    username: "ADMIN"
    password: "Welcome_12345!"
    maxPoolSize: 5
  oracleMongoApi:
    uri: "mongodb://ADMIN:Welcome_12345!@localhost:27018/admin?authMechanism=PLAIN&authSource=$external&tls=true&tlsInsecure=true&loadBalanced=true&retryWrites=false"
    database: "ADMIN"
